### ISSUE TITLE
whenever I put slotlock into my mods folder I cant join anything on minecraft

### ISSUE THREAD

**Issue by royalss-code** [lucaargolo/slotlock#3]
Minecraft boots up perfectly fine, its when I try and join any multiplayer server including hypixel it gets stuck on the "joining world" screen and will never load. I have tried taking out all mods and it works and then I put in slot lock and it doesnt, I have reinstalled slot lock, fabric and minecraft and still the same issue. 

any fixes please let me know

**Comment by RemagOfficial** [comment]
we need more information, give us a log

**Comment by royalss-code** [comment]
How would i get said logs

**Comment by royalss-code** [comment]
[latest.log](https://github.com/lucaargolo/slotlock/files/6409701/latest.log)

**Comment by royalss-code** [comment]
> we need more information, give us a log

any ideas?  i sent the log
[latest.log](https://github.com/lucaargolo/slotlock/files/6409721/latest.log)

**Comment by RemagOfficial** [comment]
could be a broken config

**Comment by royalss-code** [comment]
> could be a broken config

how would i fix this then?

**Comment by lucaargolo** [comment]
Looks like you have a corrupted slotlock.json file. It isn't supposed to crash your game tho so this is definitely a bug I'll have to fix. But for now, you may try deleting the corrupted file from your .minecraft.
